version: "3.8"

services:
  rabbitmq:
    hostname: rabbit
    image: rabbitmq:3.8.19-rc.1-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:6.2-rc3-alpine3.13
    ports:
      - "6379:6379"

  celery-server:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    command: sh ./run_web.sh
    volumes:
      - .:/Categorizer
    ports:
      - "8000:8000"
    links:
      - rabbit
      - redis

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh ./run_celery.sh
    volumes:
      - .:/Categorizer
    links:
      - rabbit
      - redis
    depends_on:
      - rabbit
