MAPPINGS = {
    0: ['computer science'],
    1: ['physics'],
    2: ['economy'],
    3: ['physics'],
    4: ['physics'],
    5: ['mathematics'],
    6: ['mathematics', 'biology'],
    8: ['economy'],
    9: ['computer science'],
    10: ['mathematics', 'physics'],
    11: ['mathematics'],
    12: ['economy'],
    13: ['physics'],
    14: ['computer science'],
    15: ['computer science'],
    16: ['mathematics'],
    17: ['physics'],
    18: ['physics'],
    19: ['biology', 'computer science'],
    20: ['biology'],
    21: ['economy'],
    23: ['biology'],
    25: ['biology'],
    26: ['biology'],
    27: ['mathematics', 'physics'],
    28: ['biology'],
    29: ['computer science', 'mathematics'],
}
